### ISSUE TITLE
The Plugin returns unknown state with ok status

### ISSUE THREAD

**Issue by mabfuss** [NETWAYS/check_sensorProbe2plus#4]
The check returns status unknown, but the plugin output returns ok.
![check_akcp](https://user-images.githubusercontent.com/64195103/193245491-091669d2-e8e9-4540-899e-db8682a25e7a.jpg)

**Comment by mabfuss** [comment]
No ideas???

**Comment by RincewindsHat** [comment]
I guess the problem lies somewhere in the internal logic, but I haven't had the time to take a look at it, sorry :-(

**Comment by RincewindsHat** [comment]
@mabfuss Could you execute the check with `-vv` to see if the output provides any help?
Also, which version are you using?

**Comment by mabfuss** [comment]
![grafik](https://user-images.githubusercontent.com/64195103/195086757-aed3ee9b-89ef-4dae-b618-6089b66acee2.png)

**Comment by mabfuss** [comment]
Version 1.0

**Comment by RincewindsHat** [comment]
@mabfuss Could you test it with the current master, to see if the problem still exists?

**Comment by mabfuss** [comment]
It works. Thanks!

Regards.
Maik
